name: WordPress Cache Prewarmer

on:
  schedule:
- cron: '0 */6 * * *'  # 0h, 6h, 12h, 18h UTC
  workflow_dispatch:

jobs:
  preload-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Installation des dependances
        run: npm install
      
      - name: Prechargement du cache
        run: node preload.js
